export enum Icons {
	CALENDAR_FULL = 'icon-calendar-full',
	CALENDAR_OUTLINE = 'icon-calendar-outline',
	HOME_FULL = 'icon-home-full',
	HOME_OUTLINE = 'icon-home-outline',
	PROFILE_FULL = 'icon-profile-full',
	PROFILE_OUTLINE = 'icon-profile-outline',
	SETTINGS_FULL = 'icon-settings-full',
	SETTINGS_OUTLINE = 'icon-settings-outline',
	ACCEPTED = 'icon-accepted',
	ADD = 'icon-add',
	ARROW = 'icon-arrow',
	ATTACH = 'icon-attach',
	BBOKMARKS = 'icon-bookmarks',
	CHAT = 'icon-chat',
	CHECK_DONE = 'icon-check-done',
	CHEVRON = 'icon-chevron',
	CLOCK = 'icon-clock',
	CLOSE = 'icon-close',
	COPY_PASTE = 'icon-copy-paste',
	DATE = 'icon-date',
	DENIED = 'icon-denied',
	FILTER = 'icon-filter',
	FRIENDS_FULL = 'icon-friends-full',
	FRIENDS_OUTLINE = 'icon-friends-outline',
	IMAGE = 'icon-image',
	INFO = 'icon-info',
	INVITATI = 'icon-invitati',
	INVITE = 'icon-invite',
	LINK = 'icon-link',
	LOCATION_FULL = 'icon-location-full',
	LOCATION_OUTLINE = 'icon-location-outline',
	MEETBALL = 'icon-meetball',
	NOTIFICATION_OUTLINE = 'icon-notification-outline',
	NOTIFICATION_FULL = 'icon-notification-full',
	RESEARCH = 'icon-research',
	SEARCH = 'icon-search',
	SHARE = 'icon-share',
	SONDAGGIO = 'icon-sondaggio',
	TRASH = 'icon-trash',
	UPLOAD = 'icon-upload',
	WHATSAPP = 'icon-whatsapp'
}

export enum Backgrounds {
	LOGIN = '/backgrounds/login.svg'
}
