export enum Icons {
	CALENDAR_FULL = '/icons/calendar-full.svg',
	CALENDAR_OUTLINE = '/icons/calendar-outline.svg',
	HOME_FULL = '/icons/home-full.svg',
	HOME_OUTLINE = '/icons/home-outline.svg',
	PROFILE_FULL = '/icons/profile-full.svg',
	PROFILE_OUTLINE = '/icons/profile-outline.svg',
	SETTINGS_FULL = '/icons/settings-full.svg',
	SETTINGS_OUTLINE = '/icons/settings-outline.svg',
	ACCEPTED = '/icons/accepted.svg',
	ADD = '/icons/add.svg',
	ARROW = '/icons/arrow.svg',
	ATTACh = '/icons/attach.svg',
	BBOKMARKS = '/icons/bookmarks.svg',
	CHAT = '/icons/chat.svg',
	CHECK_DONE = '/icons/check-done.svg',
	CHEVRON = '/icons/chevron.svg',
	CLOCK = '/icons/clock.svg',
	CLOSE = '/icons/close.svg',
	COPY_PASTE = '/icons/copy-paste.svg',
	DATE = '/icons/date.svg',
	RIGHT_ARROW = '/icons/right-arrow.svg',
	DENIED = '/icons/denied.svg',
	EDIT = '/icons/edit.svg',
	FILTER = '/icons/filter.svg',
	FRIENDS_FULL = '/icons/friends-full.svg',
	FRIENDS_OUTLINE = '/icons/friends-outline.svg',
	IMAGE = '/icons/image.svg',
	INFO = '/icons/info.svg',
	INVITATI = '/icons/invitati.svg',
	INVITE = '/icons/invite.svg',
	LINK = '/icons/link.svg',
	LOCATION_FULL = '/icons/location-full.svg',
	LOCATION_OUTLINE = '/icons/location-outline.svg',
	MEETBALL = '/icons/meetball.svg',
	NOTIFICATION_OUTLINE = '/icons/notification-outline.svg',
	NOTIFICATION_FULL = '/icons/notification-full.svg',
	RESEARCH = '/icons/research.svg',
	SEARCH = '/icons/search.svg',
	SHARE = '/icons/share.svg',
	SONDAGGIO = '/icons/sondaggio.svg',
	TRASH = '/icons/trash.svg',
	UPLOAD = '/icons/upload.svg',
	WHATSAPP = '/icons/whatsapp.svg'
}

export enum Backgrounds {
	LOGIN = '/backgrounds/login.svg'
}
